/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle001: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
    Ctrl_ArmPole_IK_Left: THREE.Bone
    Ctrl_Hand_IK_Left: THREE.Bone
    Ctrl_ArmPole_IK_Right: THREE.Bone
    Ctrl_Hand_IK_Right: THREE.Bone
    Ctrl_Foot_IK_Left: THREE.Bone
    Ctrl_LegPole_IK_Left: THREE.Bone
    Ctrl_Foot_IK_Right: THREE.Bone
    Ctrl_LegPole_IK_Right: THREE.Bone
    Ctrl_Master: THREE.Bone
  }
  materials: {
    corpo: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Dance' | 'Dance2' | 'Excited' | 'Idle' | 'Punch' | 'Salute' | 'StrafeLeft' | 'StrafeRight' | 'Walking' | 'WalkingB' | 'Waving'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/FullMushy-transformed.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      Circle: nodes.Circle001,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  const group = useRef<THREE.Group>()
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Mushy">
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
          <primitive object={nodes.Ctrl_Master} />
          <instances.Circle name="Circle001" />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/FullMushy-transformed.glb')
